"""
domain_baseline_day7 — 2단계 도메인 테이블 일괄 생성.

Revision ID: c18bc480b9e7
Revises: 0001_enable_postgis
Create Date: 2026-09-13

포함 테이블
-----------
sites, farms, rooms, racks,
sensors, actuators,
simulation_runs, weather_snapshots,
farm_states, sensor_readings,
control_rules, control_commands, control_events,
fault_injections

주의
----
- PostGIS/tiger 시스템 테이블은 절대 drop 하지 않는다 (autogenerate 노이즈 제거).
- sites.location 의 GiST 인덱스는 GeoAlchemy2 가 컬럼 생성 시 자동으로 만든다.
"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c18bc480b9e7'
down_revision: str | Sequence[str] | None = '0001_enable_postgis'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """FarmTwin 도메인 스키마를 생성한다."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 가 Geography 컬럼 생성 시 GiST 인덱스(idx_sites_location)를 자동 생성한다.
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_farms_site_code')
    )
    op.create_index(op.f('ix_farms_site_id'), 'farms', ['site_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'code', name='uq_rooms_farm_code')
    )
    op.create_index(op.f('ix_rooms_farm_id'), 'rooms', ['farm_id'], unique=False)
    op.create_table('actuators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('actuator_type', sa.Enum('hvac', 'ventilation_fan', 'dehumidifier', 'irrigation_pump', 'led', name='actuatortype', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('off', 'on', 'auto', name='actuatormode', native_enum=False, length=16), server_default='off', nullable=False),
    sa.Column('output_ratio', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('output_ratio >= 0 AND output_ratio <= 1', name='ck_actuators_output_ratio'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'code', name='uq_actuators_room_code')
    )
    op.create_index(op.f('ix_actuators_actuator_type'), 'actuators', ['actuator_type'], unique=False)
    op.create_index(op.f('ix_actuators_room_id'), 'actuators', ['room_id'], unique=False)
    op.create_table('control_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Enum('temperature', 'humidity', 'co2', 'substrate_moisture', 'ppfd', name='sensortype', native_enum=False, length=32), nullable=False),
    sa.Column('comparator', sa.Enum('gt', 'gte', 'lt', 'lte', name='rulecomparator', native_enum=False, length=8), nullable=False),
    sa.Column('start_threshold', sa.Float(), nullable=False),
    sa.Column('stop_threshold', sa.Float(), nullable=False),
    sa.Column('target_actuator_type', sa.Enum('hvac', 'ventilation_fan', 'dehumidifier', 'irrigation_pump', 'led', name='actuatortype', native_enum=False, length=32), nullable=False),
    sa.Column('target_mode', sa.Enum('off', 'on', 'auto', name='actuatormode', native_enum=False, length=16), nullable=False),
    sa.Column('target_output_ratio', sa.Float(), nullable=False),
    sa.Column('cooldown_seconds', sa.Float(), nullable=False),
    sa.Column('min_on_seconds', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cooldown_seconds >= 0', name='ck_control_rules_cooldown_nonneg'),
    sa.CheckConstraint('min_on_seconds >= 0', name='ck_control_rules_min_on_nonneg'),
    sa.CheckConstraint('priority >= 0', name='ck_control_rules_priority_nonneg'),
    sa.CheckConstraint('target_output_ratio >= 0 AND target_output_ratio <= 1', name='ck_control_rules_output_ratio'),
    sa.CheckConstraint('version >= 1', name='ck_control_rules_version_positive'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'name', 'version', name='uq_control_rules_room_name_version')
    )
    op.create_index(op.f('ix_control_rules_farm_id'), 'control_rules', ['farm_id'], unique=False)
    op.create_index('ix_control_rules_room_enabled_priority', 'control_rules', ['room_id', 'enabled', 'priority'], unique=False)
    op.create_index(op.f('ix_control_rules_room_id'), 'control_rules', ['room_id'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'code', name='uq_racks_room_code')
    )
    op.create_index(op.f('ix_racks_room_id'), 'racks', ['room_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('created', 'running', 'paused', 'stopped', 'failed', name='simulationstatus', native_enum=False, length=16), server_default='created', nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('weather_mode', sa.Enum('API', 'REPLAY', 'SYNTHETIC', name='weathermode', native_enum=False, length=16), server_default='SYNTHETIC', nullable=False),
    sa.Column('environment_model_version', sa.String(length=64), server_default='v1', nullable=False),
    sa.Column('simulation_time_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('time_scale', sa.Float(), server_default='1', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('worker_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_farm_id'), 'simulation_runs', ['farm_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_room_id'), 'simulation_runs', ['room_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_status'), 'simulation_runs', ['status'], unique=False)
    op.create_table('control_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('actuator_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'cancelled', name='controlcommandstatus', native_enum=False, length=16), nullable=False),
    sa.Column('desired_mode', sa.Enum('off', 'on', 'auto', name='actuatormode', native_enum=False, length=16), nullable=False),
    sa.Column('desired_output_ratio', sa.Float(), nullable=False),
    sa.Column('simulation_time', sa.Float(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint('desired_output_ratio >= 0 AND desired_output_ratio <= 1', name='ck_control_commands_output_ratio'),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['control_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_control_commands_idempotency_key')
    )
    op.create_index(op.f('ix_control_commands_actuator_id'), 'control_commands', ['actuator_id'], unique=False)
    op.create_index('ix_control_commands_actuator_id_issued_at', 'control_commands', ['actuator_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_control_commands_rule_id'), 'control_commands', ['rule_id'], unique=False)
    op.create_index('ix_control_commands_run_simulation_time', 'control_commands', ['simulation_run_id', 'simulation_time'], unique=False)
    op.create_index(op.f('ix_control_commands_simulation_run_id'), 'control_commands', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_control_commands_status'), 'control_commands', ['status'], unique=False)
    op.create_table('farm_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('co2_ppm', sa.Float(), nullable=False),
    sa.Column('substrate_moisture_pct', sa.Float(), nullable=False),
    sa.Column('ppfd_umol', sa.Float(), nullable=False),
    sa.Column('simulation_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_farm_states_version_positive'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', name='uq_farm_states_room')
    )
    op.create_index(op.f('ix_farm_states_farm_id'), 'farm_states', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_states_room_id'), 'farm_states', ['room_id'], unique=False)
    op.create_index(op.f('ix_farm_states_simulation_run_id'), 'farm_states', ['simulation_run_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('rack_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sensor_type', sa.Enum('temperature', 'humidity', 'co2', 'substrate_moisture', 'ppfd', name='sensortype', native_enum=False, length=32), nullable=False),
    sa.Column('unit', sa.Enum('C', '%', 'ppm', 'umol/m2/s', 'ratio', 'on_off', name='unit', native_enum=False, length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), server_default='v1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'code', name='uq_sensors_room_code')
    )
    op.create_index(op.f('ix_sensors_rack_id'), 'sensors', ['rack_id'], unique=False)
    op.create_index(op.f('ix_sensors_room_id'), 'sensors', ['room_id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_type'), 'sensors', ['sensor_type'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('API', 'REPLAY', 'SYNTHETIC', name='weathermode', native_enum=False, length=16), nullable=False),
    sa.Column('outdoor_temperature_c', sa.Float(), nullable=False),
    sa.Column('outdoor_humidity_pct', sa.Float(), nullable=False),
    sa.Column('simulation_time', sa.Float(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_run_id', 'sequence', name='uq_weather_snapshots_run_sequence')
    )
    op.create_index(op.f('ix_weather_snapshots_simulation_run_id'), 'weather_snapshots', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_simulation_time'), 'weather_snapshots', ['simulation_time'], unique=False)
    op.create_table('control_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('applied', 'stopped', 'failed', 'rejected', name='controleventtype', native_enum=False, length=16), nullable=False),
    sa.Column('actual_output_ratio', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('simulation_time', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['control_commands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_events_command_id'), 'control_events', ['command_id'], unique=False)
    op.create_index('ix_control_events_command_id_simulation_time', 'control_events', ['command_id', 'simulation_time'], unique=False)
    op.create_index(op.f('ix_control_events_event_type'), 'control_events', ['event_type'], unique=False)
    op.create_index('ix_control_events_run_simulation_time', 'control_events', ['simulation_run_id', 'simulation_time'], unique=False)
    op.create_index(op.f('ix_control_events_simulation_run_id'), 'control_events', ['simulation_run_id'], unique=False)
    op.create_table('fault_injections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('fault_type', sa.Enum('spike', 'stuck', 'dropout', name='faulttype', native_enum=False, length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('stuck_value', sa.Float(), nullable=True),
    sa.Column('start_simulation_time', sa.Float(), nullable=False),
    sa.Column('end_simulation_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_simulation_time IS NULL OR end_simulation_time >= start_simulation_time', name='ck_fault_injections_time_order'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fault_injections_fault_type'), 'fault_injections', ['fault_type'], unique=False)
    op.create_index('ix_fault_injections_run_sensor_active', 'fault_injections', ['simulation_run_id', 'sensor_id', 'active'], unique=False)
    op.create_index('ix_fault_injections_run_start_time', 'fault_injections', ['simulation_run_id', 'start_simulation_time'], unique=False)
    op.create_index(op.f('ix_fault_injections_sensor_id'), 'fault_injections', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_fault_injections_simulation_run_id'), 'fault_injections', ['simulation_run_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('C', '%', 'ppm', 'umol/m2/s', 'ratio', 'on_off', name='unit', native_enum=False, length=32), nullable=False),
    sa.Column('quality', sa.Enum('good', 'suspect', 'bad', 'missing', 'stale', name='readingquality', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('simulated', 'replay', 'load_generator', name='readingsource', native_enum=False, length=32), nullable=False),
    sa.Column('sensor_model_version', sa.String(length=64), nullable=False),
    sa.Column('simulation_time', sa.Float(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence >= 0', name='ck_sensor_readings_sequence_nonneg'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_run_id', 'sequence', name='uq_sensor_readings_run_sequence')
    )
    op.create_index(op.f('ix_sensor_readings_farm_id'), 'sensor_readings', ['farm_id'], unique=False)
    op.create_index('ix_sensor_readings_farm_id_simulation_time', 'sensor_readings', ['farm_id', 'simulation_time'], unique=False)
    op.create_index(op.f('ix_sensor_readings_quality'), 'sensor_readings', ['quality'], unique=False)
    op.create_index(op.f('ix_sensor_readings_room_id'), 'sensor_readings', ['room_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index('ix_sensor_readings_sensor_id_simulation_time', 'sensor_readings', ['sensor_id', 'simulation_time'], unique=False)
    op.create_index(op.f('ix_sensor_readings_simulation_run_id'), 'sensor_readings', ['simulation_run_id'], unique=False)


def downgrade() -> None:
    """Drop FarmTwin domain tables only. Do not touch PostGIS/tiger system tables."""
    op.drop_index(op.f('ix_sensor_readings_simulation_run_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_sensor_id_simulation_time', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_room_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_quality'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_farm_id_simulation_time', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_farm_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_fault_injections_simulation_run_id'), table_name='fault_injections')
    op.drop_index(op.f('ix_fault_injections_sensor_id'), table_name='fault_injections')
    op.drop_index('ix_fault_injections_run_start_time', table_name='fault_injections')
    op.drop_index('ix_fault_injections_run_sensor_active', table_name='fault_injections')
    op.drop_index(op.f('ix_fault_injections_fault_type'), table_name='fault_injections')
    op.drop_table('fault_injections')
    op.drop_index(op.f('ix_control_events_simulation_run_id'), table_name='control_events')
    op.drop_index('ix_control_events_run_simulation_time', table_name='control_events')
    op.drop_index(op.f('ix_control_events_event_type'), table_name='control_events')
    op.drop_index('ix_control_events_command_id_simulation_time', table_name='control_events')
    op.drop_index(op.f('ix_control_events_command_id'), table_name='control_events')
    op.drop_table('control_events')
    op.drop_index(op.f('ix_weather_snapshots_simulation_time'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_simulation_run_id'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_sensors_sensor_type'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_room_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_rack_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_farm_states_simulation_run_id'), table_name='farm_states')
    op.drop_index(op.f('ix_farm_states_room_id'), table_name='farm_states')
    op.drop_index(op.f('ix_farm_states_farm_id'), table_name='farm_states')
    op.drop_table('farm_states')
    op.drop_index(op.f('ix_control_commands_status'), table_name='control_commands')
    op.drop_index(op.f('ix_control_commands_simulation_run_id'), table_name='control_commands')
    op.drop_index('ix_control_commands_run_simulation_time', table_name='control_commands')
    op.drop_index(op.f('ix_control_commands_rule_id'), table_name='control_commands')
    op.drop_index('ix_control_commands_actuator_id_issued_at', table_name='control_commands')
    op.drop_index(op.f('ix_control_commands_actuator_id'), table_name='control_commands')
    op.drop_table('control_commands')
    op.drop_index(op.f('ix_simulation_runs_status'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_room_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_farm_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_racks_room_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_control_rules_room_id'), table_name='control_rules')
    op.drop_index('ix_control_rules_room_enabled_priority', table_name='control_rules')
    op.drop_index(op.f('ix_control_rules_farm_id'), table_name='control_rules')
    op.drop_table('control_rules')
    op.drop_index(op.f('ix_actuators_room_id'), table_name='actuators')
    op.drop_index(op.f('ix_actuators_actuator_type'), table_name='actuators')
    op.drop_table('actuators')
    op.drop_index(op.f('ix_rooms_farm_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_farms_site_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_table('sites')
